insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Red, Gamay Noir', 'Office Supplies', 1544, '2023-05-09', 699.35, 'Candida Plus');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cauliflower', 'International Foods', 208, '2023-06-30', 507.76, 'Opcon-A');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Mushroom - Chantrelle, Fresh', 'Gluten-Free Products', 895, '2023-09-04', 172.19, 'Dibasic Sodium Phosphate, Monobasic Potassium Phosphate and Monobasic Sodium Phosphate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Peach - Halves', 'Deli', 1710, '2023-12-28', 1382.04, 'VIGAMOX');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Pita, Mini', 'Canned Goods', 1063, '2024-01-21', 769.15, 'Simvastatin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Liqueur - Melon', 'Organic Products', 627, '2023-06-01', 1573.47, 'ALFENTANIL HYDROCHLORIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Muffin - Banana Nut Individual', 'Breakfast Foods', 138, '2023-08-07', 958.65, 'ISA KNOX AGELESS MOIST SERUM TWO WAY CAKE 23 (REFILL)');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Eggplant - Baby', 'Breakfast Foods', 1635, '2023-09-22', 955.68, 'Primlev');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beans - Wax', 'Cleaning Supplies', 807, '2024-02-19', 1833.8, 'ALDACTAZIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Tamarillo', 'Baby Care', 513, '2023-09-22', 1169.18, 'Medique Guaicon DMS');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Peach - Halves', 'Canned Goods', 1027, '2023-06-17', 584.73, 'DR. WALTONS COOL AND HOT ANALGESIC');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Muskox - French Rack', 'Snacks', 752, '2023-11-09', 593.43, 'Fluconazole');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Sage Derby', 'Beauty and Skincare', 1537, '2024-01-11', 1666.55, 'Disney Antibacterial Hand Wipes - TOY STORY, CARS, MONSTERS UNIVERSITY');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Italian Roll With Herbs', 'Baby Care', 1803, '2023-03-28', 589.52, 'Mepivacaine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Sole - Dover, Whole, Fresh', 'Health and Wellness', 1394, '2023-11-11', 321.78, 'Quetiapine fumarate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Stock - Beef, White', 'Baking Supplies', 569, '2023-09-06', 516.91, 'Amlodipine Besylate and Benazepril Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Foil Cont Round', 'Household Essentials', 1120, '2023-12-25', 671.44, 'Bacteriostatic Sodium Chloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork - Side Ribs', 'Snacks', 1122, '2023-08-31', 1330.28, 'Nitrofurantoin (macrocrystals)');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Vanilla Beans', 'Household Essentials', 342, '2023-11-25', 116.19, 'Severe Cold and Flu');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beans - Black Bean, Dry', 'International Foods', 989, '2023-09-06', 725.52, 'Indomethacin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Snapple Raspberry Tea', 'Baby Care', 409, '2023-05-11', 994.44, 'equaline all day pain relief');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Hersey Shakes', 'Deli', 1078, '2023-06-20', 800.68, 'DiorSnow White Reveal Instant Spot Concealer SPF 50 Light Beige 020');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wonton Wrappers', 'Health and Wellness', 1914, '2023-09-15', 1517.65, 'BABY TINY COLD');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup - Campbells, Spinach Crm', 'Personal Care', 1448, '2024-03-07', 306.08, 'Being Well Body');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Nantucket - 518ml', 'Frozen Foods', 1279, '2023-06-01', 743.98, 'rexall allergy relief');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Waffle Stix', 'Pet Supplies', 1911, '2023-06-11', 453.78, 'NMC Magic Serum');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chocolate - Mi - Amere Semi', 'Organic Products', 219, '2023-08-20', 809.3, 'Naturasil');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Peller Estates Late', 'Frozen Foods', 976, '2023-09-20', 1558.8, 'Trifluoperazine Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup Campbells Mexicali Tortilla', 'Frozen Foods', 1538, '2023-11-30', 1072.65, 'pain relief');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pastry - French Mini Assorted', 'Baking Supplies', 418, '2023-08-31', 1132.42, 'Tamsulosin hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bagelers - Cinn / Brown Sugar', 'Paper Products', 495, '2024-01-08', 1418.85, 'Lorazepam');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beef - Kobe Striploin', 'Cleaning Supplies', 537, '2024-02-28', 1699.93, 'Hydralazine Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Oil - Coconut', 'Condiments', 1445, '2023-11-29', 374.67, 'Lamotrigine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cakes Assorted', 'Cleaning Supplies', 888, '2023-05-10', 1393.83, 'ENALAPRIL MALEATE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Long Island Ice Tea', 'Beauty and Skincare', 942, '2023-10-18', 1751.98, 'LBEL');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Yogurt - French Vanilla', 'Beauty and Skincare', 66, '2024-01-01', 1134.95, 'Axe');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cheese - St. Paulin', 'Beauty and Skincare', 61, '2023-09-12', 623.46, 'SINGULAIR');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bag - Clear 7 Lb', 'Paper Products', 1003, '2023-11-10', 547.3, 'Moisturizing Face Screen Light Tint SPF 30');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Sake', 'Beauty and Skincare', 716, '2023-07-27', 211.76, 'Lidocaine Hydrochloride and Epinephrine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cilantro / Coriander - Fresh', 'Condiments', 1868, '2024-03-12', 512.74, 'Acyclovir');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Lentils - Green Le Puy', 'Health and Wellness', 861, '2023-05-15', 1645.32, 'Stool Softener');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Olive Dinner Roll', 'Beverages', 1882, '2023-06-26', 1910.36, 'Leader sleep aid');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Water - Mineral, Natural', 'Bakery', 937, '2023-09-17', 859.61, 'NORLYROC');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Red, Concha Y Toro', 'Paper Products', 271, '2023-07-29', 691.41, 'Risedronate Sodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Vinegar - Champagne', 'Personal Care', 138, '2024-03-05', 1878.32, 'SODIUM SULFACETAMIDE and SULFUR');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Ham - Procutinni', 'Pet Supplies', 757, '2023-10-15', 1208.91, 'PHS Hair Science Fem Hair Loss Tonic');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup Campbells Mexicali Tortilla', 'Deli', 1860, '2024-03-07', 1904.69, 'Gattex');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Rum - Mount Gay Eclipes', 'Beverages', 668, '2023-04-27', 1564.55, 'ROPINIROLE HYDROCHLORIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soy Protein', 'Baby Care', 1497, '2023-07-30', 858.18, 'Lotrimin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Artichokes - Jerusalem', 'Produce', 1020, '2023-11-11', 1030.55, 'XENADERM');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Anchovy Paste - 56 G Tube', 'Bakery', 1256, '2023-09-04', 91.52, 'Mirtazapine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Jam - Marmalade, Orange', 'Gluten-Free Products', 810, '2023-12-12', 1094.07, 'Nortriptyline Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cod - Salted, Boneless', 'Household Essentials', 135, '2023-06-30', 1376.69, 'ATORVASTATIN CALCIUM');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Ecolab - Balanced Fusion', 'Snacks', 1634, '2023-03-21', 974.15, 'Carbidopa, Levodopa and Entacapone');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Kippers - Smoked', 'Snacks', 427, '2023-10-30', 1955.58, 'Neostigmine Methylsulfate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Raisin - Dark', 'Paper Products', 519, '2023-10-15', 1659.48, 'Ofloxacin Otic');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - White, Lindemans Bin 95', 'Produce', 1404, '2023-10-07', 955.2, 'Nivea A Kiss of Shimmer Radiant Lip Care');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cheese - Oka', 'Meat', 1913, '2023-09-09', 670.96, 'ED APAP');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Shrimp - Black Tiger 13/15', 'Cleaning Supplies', 683, '2024-01-20', 1853.6, 'dg health allergy');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - White, Lindemans Bin 95', 'Beverages', 1459, '2023-07-21', 793.1, 'Retin-A MICRO');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Tomatoes Tear Drop', 'Beverages', 1440, '2023-07-23', 804.8, 'Prednisone');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beans - Fine', 'Cleaning Supplies', 1161, '2023-09-29', 147.51, 'Veneno de Abeja');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Tart Shells - Savory, 2', 'Breakfast Foods', 1729, '2023-12-01', 1117.99, 'LISINOPRIL');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Wyndham Estate Bin 777', 'Pet Supplies', 867, '2023-04-09', 906.74, 'Sugar Free Mountain Herb Cough Suppressant Throat Drops');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pasta - Cappellini, Dry', 'Frozen Foods', 466, '2023-10-23', 1929.84, 'Mirtazapine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Banana Turning', 'Meat', 307, '2024-03-12', 109.36, 'MORELLA CERIFERA POLLEN');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Tortillas - Flour, 12', 'Produce', 1605, '2023-07-31', 1371.81, 'VISIBLE DIFFERENCE MULTI TARGETED BB CREAM BROAD SPECTRUM SUNSCREEN SPF 30 SHADE 1');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Praline Paste', 'Bakery', 682, '2023-09-02', 539.55, 'Progesterone Injection');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Water - Tonic', 'Snacks', 834, '2024-01-11', 1583.88, 'ALOE VESTA ANTIFUNGAL');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Salmon Steak - Cohoe 8 Oz', 'Health and Wellness', 1572, '2023-08-11', 551.94, 'Noble Lion Medicated Balm');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beef Ground Medium', 'International Foods', 1113, '2024-02-04', 811.14, 'Diphenhydramine HCL');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Persimmons', 'Cleaning Supplies', 1260, '2024-02-24', 1152.2, 'Precose');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Lemonade - Pineapple Passion', 'International Foods', 375, '2023-11-03', 64.84, 'Dial Gold Bar');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Roe - Lump Fish, Red', 'Beauty and Skincare', 1332, '2023-08-25', 1393.59, 'Feather Mixture');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Turkey - Breast, Boneless Sk On', 'Deli', 1339, '2023-11-20', 954.87, 'ESIKA Silk Skin SPF 9');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Catfish - Fillets', 'Condiments', 1858, '2023-10-08', 1814.22, 'Dovonex');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Veal - Round, Eye Of', 'Paper Products', 1217, '2023-10-30', 1628.75, 'Glyset');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Lid Coffee Cup 8oz Blk', 'Pasta and Rice', 1924, '2023-04-25', 1041.96, 'Leflunomide');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Puree - Guava', 'Health and Wellness', 353, '2023-04-15', 1789.78, 'Cactus Crataegus');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Apron', 'Beverages', 1018, '2023-07-17', 1986.18, 'PRAVASTATIN SODIUM');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Butter Ripple - Phillips', 'Frozen Foods', 1652, '2023-12-22', 1930.74, 'Hydrocortisone Valerate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Blueberries', 'Condiments', 1464, '2023-09-17', 1818.25, 'ACYCLOVIR');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Magnotta - Cab Franc', 'Baby Care', 238, '2023-07-01', 757.19, 'Prandin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Hold Up Tool Storage Rack', 'Deli', 821, '2023-05-08', 613.7, 'Buxom Show Some Skin Weightless Foundation Broad Spectrum SPF 30');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Oil - Grapeseed Oil', 'Produce', 141, '2024-01-26', 1150.22, 'A. Dust');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Tray - 12in Rnd Blk', 'Gluten-Free Products', 501, '2023-07-26', 1041.58, 'Metformin Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pasta - Agnolotti - Butternut', 'Office Supplies', 401, '2023-07-21', 1302.5, 'members mark nicotine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork - Sausage, Medium', 'Dairy', 1705, '2023-04-27', 1097.46, 'Amitriptyline Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Petit Baguette', 'Office Supplies', 1829, '2023-03-31', 397.88, 'Phenazo');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Devonshire Cream', 'Breakfast Foods', 1162, '2023-08-14', 685.63, 'Bald Cypress');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Rum - Cream, Amarula', 'Breakfast Foods', 1115, '2023-06-07', 1139.3, 'Levetiracetam');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beer - Fruli', 'Deli', 239, '2023-12-14', 845.54, 'Ondansetron Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Table Cloth 53x69 White', 'Cleaning Supplies', 1102, '2023-11-05', 274.61, 'Sal de Uvas Picot');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Mushroom - Porcini, Dry', 'Baby Care', 773, '2023-10-05', 939.23, 'FAMOTIDINE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Water - Mineral, Carbonated', 'Organic Products', 176, '2024-01-08', 844.78, 'YERVOY');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Flavouring - Orange', 'International Foods', 1554, '2023-08-01', 1278.92, 'TopCare Daytime Severe Cold and Cough');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Muffin Hinge Container 6', 'Canned Goods', 1154, '2023-11-08', 464.19, 'REPAGLINIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup - Campbells, Lentil', 'Beverages', 1071, '2023-12-29', 827.95, 'Sunscreen Sport Lip');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pepper - Black, Whole', 'Frozen Foods', 1040, '2023-04-05', 737.2, 'Warfarin Sodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chickensplit Half', 'Dairy', 873, '2023-08-13', 1066.97, 'Phytonadione');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wooden Mop Handle', 'Personal Care', 492, '2023-10-30', 591.8, 'Oxygen');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Broom - Angled', 'Condiments', 754, '2023-05-01', 1898.73, 'COREG');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Puree - Blackcurrant', 'Beverages', 1499, '2023-12-05', 1216.95, 'Stool Softener with Laxative');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('7up Diet, 355 Ml', 'Baking Supplies', 1303, '2024-01-15', 1060.04, 'Xylocaine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Broom - Angled', 'Baking Supplies', 1710, '2023-12-28', 1981.7, 'Homeopathic Tension Headache Formula');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beef - Tenderloin', 'Snacks', 1572, '2024-02-03', 940.14, 'Risedronate Sodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Herb Du Provence - Primerba', 'Pasta and Rice', 190, '2023-11-06', 581.78, 'Pore Rescue');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Toasted Head', 'Bakery', 74, '2023-06-28', 385.71, 'DDF Daily Protective Moisturizer');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chinese Foods - Thick Noodles', 'Organic Products', 1392, '2023-03-16', 1836.38, 'Little Remedies Little Tummys Laxative Drops');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Longos - Chicken Wings', 'Beauty and Skincare', 1918, '2024-01-24', 847.18, 'CLONIDINE HYDROCHLORIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Daikon Radish', 'Organic Products', 1067, '2023-04-02', 657.86, 'Nitrofurantion Macrocrystals');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cheese - Brie Roitelet', 'Pasta and Rice', 1465, '2023-12-16', 1666.79, 'Childrens Cough Relief');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Praline Paste', 'Bakery', 1989, '2023-11-15', 129.89, 'Levofloxacin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Rice Wine - Aji Mirin', 'Gluten-Free Products', 997, '2023-11-06', 871.36, 'Topamax');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Halibut - Steaks', 'Canned Goods', 875, '2023-08-16', 1540.72, 'WHITE MULBERRY POLLEN');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread Crumbs - Panko', 'Household Essentials', 1314, '2023-04-04', 782.04, 'ELF Mineral Lip Tint SPF 8');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beef - Inside Round', 'Bakery', 1280, '2024-02-14', 892.61, 'KOCHIA SCOPARIA POLLEN');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beans - Long, Chinese', 'Baby Care', 1474, '2023-07-27', 1558.89, 'Alendronate Sodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Nacho Chips', 'Office Supplies', 1819, '2023-08-24', 602.3, 'Liver Drainage');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork - Tenderloin, Frozen', 'Produce', 667, '2023-11-01', 1455.89, 'Neutrogena Wet Skin Kids Beach and Pool Sunblock');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Apple - Fuji', 'Office Supplies', 1740, '2023-04-07', 380.26, 'Amoxicillin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Mace', 'Produce', 1141, '2024-01-18', 1155.12, 'Target Fancy Nancy Antibacterial Hand Glamorous Grape');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Onions - Pearl', 'Office Supplies', 402, '2023-07-28', 888.67, 'aller ease');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Malt', 'Produce', 1058, '2023-11-15', 1062.79, 'Topicort');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Hinge W Undercut', 'Snacks', 1541, '2023-05-09', 1838.21, 'Dexilant');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Zucchini - Yellow', 'Produce', 1475, '2023-03-28', 126.47, 'Arnica e pl. tota 30');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Extract - Lemon', 'Frozen Foods', 1969, '2023-08-24', 798.13, 'Golden Sunshine Far Infrared Herbal');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chicken - White Meat, No Tender', 'Office Supplies', 134, '2023-09-06', 1951.02, 'SLEEP AID');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chicken - Thigh, Bone In', 'Personal Care', 1355, '2024-01-07', 375.02, 'Aleve');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Nut - Pistachio, Shelled', 'Dairy', 1175, '2023-05-16', 663.7, 'ANTIBACTERIAL FOAMING');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cookie Dough - Chunky', 'Paper Products', 1680, '2023-04-24', 601.68, 'Gas Relief');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Merlot Vina Carmen', 'Gluten-Free Products', 1143, '2024-01-25', 1075.6, 'UNITHROID');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Energy - Boo - Koo', 'Personal Care', 959, '2023-06-16', 810.86, 'LBel');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Ostrich - Prime Cut', 'Baking Supplies', 759, '2024-01-18', 499.44, 'Suave');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Carbonated Water - Strawberry', 'Health and Wellness', 1513, '2023-10-24', 1794.89, 'Stay Awake');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork Casing', 'Snacks', 1785, '2023-09-12', 1425.7, 'Ampicillin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Coffee Beans - Chocolate', 'Baking Supplies', 165, '2023-04-24', 599.9, 'Neurotone');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Steampan - Foil', 'Bakery', 660, '2023-07-28', 1760.37, 'Night Time Cough Cherry');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Squid - Tubes / Tenticles 10/20', 'Beauty and Skincare', 1672, '2023-10-11', 1698.93, 'Zyprexa');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork - Ground', 'Dairy', 585, '2023-12-18', 1303.94, 'OMNI');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Onions - Red', 'Health and Wellness', 1215, '2023-07-20', 220.81, 'Carvedilol');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Carbonated Water - Strawberry', 'Beauty and Skincare', 1589, '2023-03-27', 374.2, 'Divalproex Sodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Lamb - Racks, Frenched', 'Canned Goods', 1802, '2024-03-08', 1291.62, 'Food - Plant Source, Brazil Nut Bertholletia excelsa');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Scallops 60/80 Iqf', 'Pasta and Rice', 832, '2023-08-23', 1133.14, 'Ethyl alcohol');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Onions - Red Pearl', 'Canned Goods', 1263, '2024-02-24', 748.83, 'Lady Speed Stick');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Mcgillicuddy Vanilla Schnap', 'Baking Supplies', 1317, '2023-10-17', 1849.66, 'Risperidone');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chocolate - Pistoles, Lactee, Milk', 'Pet Supplies', 1563, '2023-09-06', 1318.84, 'Haloperidol');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Apple - Northern Spy', 'Produce', 1573, '2023-05-05', 84.51, 'Losartan Potassium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Ecolab - Medallion', 'Meat', 495, '2023-04-29', 1139.81, 'XtraCare Vaporizing Chest Rub');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pepper - Paprika, Spanish', 'Organic Products', 181, '2023-08-30', 1827.77, 'flormar CC Magical Color Effect Color Correcting Cream Sunscreen Broad Spectrum SPF 15 CC03');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Italian Sesame Poly', 'Organic Products', 1022, '2023-05-03', 1144.58, 'IOPE B.B BB');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Boogies', 'Dairy', 791, '2023-10-04', 1847.38, 'Badger SPF 35 Sport Sunscreen Cream');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Dr. Pepper - 355ml', 'Pet Supplies', 1190, '2023-11-22', 1545.57, 'Pamidronate Disodium');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Rice Pilaf, Dry,package', 'Paper Products', 749, '2023-04-09', 1450.83, 'Norepinephrine bitartrate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Miso Paste White', 'Bakery', 1580, '2024-01-31', 1188.15, 'Benazepril Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup - Campbells, Lentil', 'Gluten-Free Products', 1654, '2023-06-09', 1755.54, 'Bupropion Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pesto - Primerba, Paste', 'Health and Wellness', 577, '2023-12-27', 1522.47, 'Nortriptyline Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Snapple Raspberry Tea', 'Snacks', 520, '2023-04-19', 1534.67, 'Naproxen');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beans - Black Bean, Canned', 'Condiments', 681, '2024-03-14', 896.81, 'DIETHYLPROPION HYDROCHLORIDE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Muskox - French Rack', 'Baking Supplies', 479, '2023-09-12', 511.25, 'YS Solution Ac control Skin Regular Mild');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Crush - Grape, 355 Ml', 'Organic Products', 1289, '2023-08-25', 1060.63, 'LBEL LEDERM 45plus Jour');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Bistro Sour', 'Personal Care', 861, '2023-04-02', 438.22, 'PAROXETINE');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Easy Off Oven Cleaner', 'Cleaning Supplies', 1983, '2023-10-08', 1133.84, 'Risperidone');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Flounder - Fresh', 'Condiments', 1301, '2024-01-08', 316.52, 'Cheat Brome Grass');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Soup - Campbells Pasta Fagioli', 'Office Supplies', 1293, '2023-05-21', 782.95, 'Morphine Sulfate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cake - Sheet Strawberry', 'Office Supplies', 1058, '2024-02-22', 467.95, 'AMERFRESH ROLL-ON ANTIPERSPIRANT DEODORANT');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Eel Fresh', 'Frozen Foods', 1098, '2023-08-21', 251.49, 'Hot Flash Rescue');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Yoplait Drink', 'Gluten-Free Products', 153, '2023-12-29', 136.05, 'Orris Root');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Glycerine', 'Frozen Foods', 592, '2024-01-04', 270.99, 'BYDUREON');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Arctic Char - Fillets', 'Condiments', 1344, '2023-04-07', 217.95, 'Lithium Carbonate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Appetizer - Lobster Phyllo Roll', 'Gluten-Free Products', 1349, '2023-12-09', 1731.31, 'Pleo Ut S');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Beef - Chuck, Boneless', 'Deli', 1072, '2024-02-23', 360.01, 'ESIKA HYDRACOLOR 2 IN 1 HIGHLY MOISTURIZING AND COLORING SPF 25');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cake - Miini Cheesecake Cherry', 'Organic Products', 1676, '2023-06-17', 1405.77, 'Australian Gold');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Russian Prince', 'Household Essentials', 1157, '2023-05-29', 592.17, 'PDI Duo-Swab Povidone-Iodine');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bandage - Fexible 1x3', 'Condiments', 742, '2023-11-30', 119.1, 'Ascorbic Acid');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Foil - Round Foil', 'Bakery', 417, '2024-03-08', 1382.29, 'APIS MELLIFICA');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Ham - Cooked Bayonne Tinned', 'Snacks', 899, '2023-04-29', 1161.96, 'Proactiv Solution Refining Mask');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Corn Muffaletta', 'Meat', 863, '2023-07-24', 1105.15, 'Thioridazine Hydrochloride');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pork - Back Ribs', 'Beverages', 1143, '2023-12-26', 1391.1, 'Medisilke');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pie Filling - Pumpkin', 'Beverages', 1366, '2024-03-13', 1525.79, 'Brontuss');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pastry - Mini French Pastries', 'Personal Care', 409, '2024-03-07', 743.96, 'Amoxicillin');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Placemat - Scallop, White', 'Pasta and Rice', 875, '2023-06-14', 1780.29, 'LEVOFLOXACIN');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Jolt Cola - Electric Blue', 'Pet Supplies', 114, '2023-04-17', 578.11, 'well at walgreens lansoprazole');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Seabream Whole Farmed', 'Bakery', 642, '2023-06-10', 1701.99, 'Neutrogena Wet Skin Kids Beach and Pool');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Drambuie', 'Household Essentials', 1623, '2024-02-21', 1994.96, 'McKesson Antimicrobial Hand');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Gelatine Leaves - Bulk', 'Gluten-Free Products', 885, '2023-06-12', 603.85, 'Acetaminophen and Codeine Phosphate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Cheese - Cottage Cheese', 'Beverages', 1251, '2023-08-20', 712.42, 'rexall night time cold and flu');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Turnip - White', 'Canned Goods', 808, '2023-07-15', 957.52, 'Tums');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Quail - Whole, Boneless', 'Breakfast Foods', 1629, '2023-03-26', 1574.28, 'Prozac');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread - Multigrain Oval', 'Dairy', 424, '2023-10-18', 1772.48, 'YES TO CARROTS FRAGRANCE-FREE DAILY FACIAL MOISTURIZER SPF15');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Dc Hikiage Hira Huba', 'International Foods', 1046, '2023-05-16', 671.26, 'Glyburide');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Burger Veggie', 'Household Essentials', 1670, '2024-01-18', 355.73, 'Chloraseptic Sore Throat');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - Rhine Riesling Wolf Blass', 'Baking Supplies', 122, '2023-12-04', 157.16, 'HAWAIIAN Tropic');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Wine - White, Ej Gallo', 'Meat', 1106, '2023-11-24', 592.02, 'Morphine Sulfate');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Pasta - Fett Alfredo, Single Serve', 'Pet Supplies', 172, '2023-04-09', 1480.85, 'Fast Freeze');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Onions - Red', 'Household Essentials', 409, '2023-07-05', 301.25, 'Isoniazid');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Chicken Breast Wing On', 'Meat', 669, '2023-09-09', 1364.68, 'Handy Solutions Dove Cool Essential Cucumber and Green Tea Scent Anti-Perspirant');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bowl 12 Oz - Showcase 92012', 'Canned Goods', 287, '2023-07-26', 683.92, 'Gengraf');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Shortbread - Cookie Crumbs', 'Baking Supplies', 223, '2023-08-20', 1096.23, 'Xalatan');
insert into Products (name, category, quantity, expiration_date, price, manufacturer) values ('Bread Base - Gold Formel', 'Baby Care', 690, '2023-07-06', 918.91, 'Gablofen');
